grocerybot/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^produce/', include('produce.urls')),
]

produce/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from . import views

app_name = 'produce'

urlpatterns = [
	# Inbound SMS view:
	url(r'^sms/$', views.sms, name='sms'),

	# List and Detail Views:
	url(r'^list/', views.SeasonalView.as_view(), name='list'),
	url(r'^(?P<pk>[0-9]+)/$', views.ProduceDetailView.as_view(), name='produce_detail'),

	# CRUD for Produce Items:
	url(r'^submit/', views.submit_new_produce, name='submit'),
	url(r'^thanks/', TemplateView.as_view(template_name='produce/thanks.html')),
	url(r'^(?P<pk>[0-9]+)/edit/$', views.ProduceUpdateView.as_view(), name='produce_edit'),
	url(r'^(?P<pk>[0-9]+)/delete/$', views.ProduceDeleteView.as_view(), name='produce_delete'),
]

produce/models.py
from __future__ import unicode_literals

from django.db import models
import datetime
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible  # only if you need to support Python 2
class Produce(models.Model):
	STATES = (
		('Alabama', 'Alabama'),
		('Alaska', 'Alaska'),
		('Arizona', 'Arizona'),
		('Arkansas', 'Arkansas'),
		('California', 'California'),
		('Colorado', 'Colorado'),
		('Connecticut', 'Connecticut'),
		('Delaware', 'Delaware'),
		('Florida', 'Florida'),
		('Georgia', 'Georgia'),
		('Hawaii', 'Hawaii'),
		('Idaho', 'Idaho'),
		('Illinois', 'Illinois') ,
		('Indiana', 'Indiana'),
		('Iowa', 'Iowa'),
		('Kansas', 'Kansas'),
		('Kentucky', 'Kentucky'),
		('Louisiana', 'Louisiana'),
		('Maine', 'Maine'),
		('Maryland', 'Maryland'),
		('Massachusetts', 'Massachusetts'),
		('Michigan', 'Michigan'),
		('Minnesota', 'Minnesota'),
		('Mississippi', 'Mississippi'),
		('Missouri', 'Missouri'),
		('Montana', 'Montana') ,
		('Nebraska', 'Nebraska'),
		('Nevada', 'Nevada'),
		('New Hampshire', 'New Hampshire'),
		('New Jersey', 'New Jersey'),
		('New Mexico', 'New Mexico'),
		('New York', 'New York'),
		('North Carolina', 'North Carolina'),
		('North Dakota', 'North Dakota'),
		('Ohio', 'Ohio'),
		('Oklahoma', 'Oklahoma'),
		('Oregon', 'Oregon'),
		('Pennsylvania', 'Pennsylvania') ,
		('Rhode Island', 'Rhode Island'),
		('South Carolina', 'South Carolina'),
		('South Dakota', 'South Dakota'),
		('Tennessee', 'Tennessee'),
		('Texas', 'Texas'),
		('Utah', 'Utah'),
		('Vermont', 'Vermont'),
		('Virginia', 'Virginia'),
		('Washington', 'Washington'),
		('West Virginia', 'West Virginia'),
		('Wisconsin', 'Wisconsin'),
		('Wyoming', 'Wyoming'),

	)
	FOOD_TYPE = (
		('Vegetable', 'Vegetable'),
		('Fruit', 'Fruit'),
		('Protein', 'Protein'),
		('Other', 'Other'),
    )

	name = models.CharField(max_length=200)
	food_type = models.CharField(max_length=200, choices=FOOD_TYPE)
	season_start = models.DateField(blank=True, null=True)
	season_end = models.DateField(blank=True, null=True)
	state = models.CharField(max_length=500, choices=STATES, default='New York')

	# Additional fields not set by users:
	# created = models.DateTimeField(auto_now_add=True, defau)

	def __str__(self):
		return 'Produce #{0} - {1} in {2}'.format(self.pk, self.name, self.state)

	def get_absolute_url(self):
		return reverse('produce_detail', args=[str(self.id)])

produce/forms.py
from django	import forms

from produce.models import	Produce

class ProduceSubmitForm(forms.ModelForm):
	class Meta:
		model = Produce
		fields = ('name', 'food_type', 'season_start', 'season_end')

produce/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, DetailView, UpdateView
from django_twilio.decorators import twilio_view
from twilio.twiml import Response
import datetime

from produce.forms import ProduceSubmitForm
from produce.models import Produce
from produce.messages import *


class SeasonalView(generic.ListView):
    """Returns a list of the produce that is in season for the current day."""
    template_name = 'produce/list.html'
    context_object_name = 'produce_list'

    def get_queryset(self):
        today = datetime.datetime.now()
        return Produce.objects.filter(season_start__lte=today, season_end__gte=today)


class ProduceDetailView(generic.DetailView):
    """Shows users a single produce entry."""

    model = Produce
    template_name = 'produce/produce_detail.html'


class ProduceUpdateView(generic.UpdateView):
    """Powers a form to edit existing Produces"""

    model = Produce
    template_name = 'produce/submit.html'
    fields = ['name', 'state', 'food_type', 'season_start', 'season_end']
    # This should be updated to be a message, using djangos message thing
    # Also probably shouldn't use reverse_lazy here - got to be better way
    success_url = reverse_lazy('list')


class ProduceDeleteView(generic.DeleteView):
    """Prompts user to confirm deletion of produce and then delete"""
    model = Produce
    success_url = reverse_lazy('list')


@twilio_view
def sms(request):
    """Receive incoming SMS messages.  Return a generic response."""
    message_body = request.POST.get('Body', '')
    incoming_number = request.POST.get('From', '')
    # This cannot be the right way to do this, but checking if the
    # user sent a produce or a location, and then responding accordingly
    query_set = Produce.objects.all()
    if query_set.filter(name__icontains=message_body):
        send_sms_produce_detail(message_body, incoming_number)
    else:
        send_sms_seasonal_produce(message_body, incoming_number)
    r = Response()
    return r


def submit_new_produce(request):
    """Add a new produce to the database from the ProduceSubmitForm."""
    if request.method == "POST":
        form = ProduceSubmitForm(request.POST)
        if form.is_valid():
            produce = form.save(commit=False)
            produce.save()
            # This thanks page is useless, should be a success message:
            return HttpResponseRedirect('/produce/thanks/')
    else:
        form = ProduceSubmitForm()
    return render(request, 'produce/submit.html', {'form': form})

produce/templates/produce/confirm_delete.html
<body>
	<div class="row">
		<div class="col-lg-9">
			<div class="page-header">
			<h1>Confirm deletion</h1>
			</div>

			<form action="" method="post">
			  {% csrf_token %}
			  <p>Are you sure you want to delete <strong>{{ object }}</strong>?</p>
			  <a class="btn btn-default" href="javascript:history.back()">Back</a>
			  <button type="submit" class="btn btn-danger">Delete</button>
			</form>
		</div>
	</div>
</body>

produce/templates/produce/list.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

<h1>Produce in Season</h1>
{% if produce_list %}
    <ul>
    {% for produce in produce_list %}
		<li>{{ produce.name }} in {{ produce.state }}</li>
	{% endfor %}
    </ul>
{% else %}
    <p>No produce are available.</p>
{% endif %}

produce/templates/produce/produce_detail.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

<div class="row">
	<div class="col-lg-9">
		<div class="page-header">
			<h1>Produce</h1>
		</div>

		<dl class="dl-horizontal">
			<dt><strong>Name:</strong></dt>
			<dd>{{ produce.name }}</dd>
			<dt><strong>Locations:</strong></dt>
			<dd>{{ produce.state }}</dd>
			<dt><strong>Season Start:</strong></dt>
			<dd>{{ produce.season_start }}</dd>
			<dt><strong>Season End:</strong></dt>
			<dd>{{ produce.season_end }}</dd>
		</dl>

	</div>
</div>

produce/templates/produce/submit.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_javascript jquery=1 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<body>
   <div class="container">
      <div class="row">
          <div class="col-md-6">
			<form method="POST">
				{% csrf_token %}
				{% bootstrap_form form %}
				{% buttons %}
				<button type="submit" class="btn btn-primary">Submit</button>
				{% endbuttons %}
			</form>
		</div>
	</div>
</body>

{% block page_css %}
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css" />
{% endblock %}

{% block page_js %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/js/bootstrap-datetimepicker.min.js"></script>

  <script type="text/javascript">
      $(function() {
          $('#id_season_start').datetimepicker({
            format: 'MM/DD/YYYY HH:mm',
            extraFormats: ['YYYY-MM-DD HH:mm:ss'],
            sideBySide: true
          });
      });
  </script>
{% endblock %}

produce/templates/produce/thanks.html
<h1>thanks</h1>
<a href="{% url 'produce:submit' %}">Submit more?</a>